Repository wtkcooley/Eventify, pull requests merged in 2023-02, with the labels that each got.

#13 bugfix fixes issue #12
  public/script.js
Labels: bug

#19 Adds major UI upgrades and addresses #14
  public/index.html
  public/script.js
  public/style.css
Labels: enhancement

#23 updates README.md
  README.md
Labels: documentation

#24 hotfix removes tmp dir
  tmp\nodejs\npm-cache/_cacache/content-v2/sha512/04/bc/ebe131a8dcc4eaa4a34042e8f93abc98cdfa16b0e0ea78f2fecbbafbb6361d11a8d1d689a3d2a4a6cb4c29989bf5a8040f21f6f3ef587010f455692fa51c
  tmp\nodejs\npm-cache/_cacache/content-v2/sha512/0b/61/241d7c17bcbb1baee7094d14b7c451efecc7ffcbd92598a0f13d313cc9ebc2a07e61f007baf58fbf94ff9a8695bdd5cae7ce03bbf1e94e93613a00f25f21
  tmp\nodejs\npm-cache/_cacache/content-v2/sha512/ec/63/ba1e08640397d81bd4d89cdc62d78ffb2bd7f9a1c70c969df35c0b92c67ec2282c6df716cd586ef217c85309251c8657d649edee2e694f7e281ebd122dcd
  tmp\nodejs\npm-cache/_cacache/index-v5/34/8e/30c54cce758990bcd1b33114c4aa8a9e5a25c152ac39d9feab22b7e13e00
  tmp\nodejs\npm-cache/_cacache/index-v5/dc/f5/c0bfb27060f61ca8e70fcb2eb1561295e496fd711ffa5e01fdd576dfd55f
  tmp\nodejs\npm-cache/_cacache/index-v5/ef/1a/c4c9b747429030b177039ac7d1c428960ea4dcf45f54dfd84b437567f4ec
  tmp\nodejs\npm-cache/_cacache/index-v5/ef/23/134a34866512795c8a5025d0b968f2e44b5be8ab3a05b400c089c32a272e
  tmp\nodejs\npm-cache/anonymous-cli-metrics.json
Labels: bug

#34 Implemented spotify login for adding users
  app.js
  public/index.html
  public/script.js
  public/user.png
Labels: enhancement, ui, feature

#35 bugfix/32 fixes expired token bug
  public/script.js
Labels: bug

#36 feature/31 adds responsive ui
  public/index.html
  public/style.css
Labels: enhancement, ui

#37 Dev/trunk
  public/index.html
  public/script.js
  public/style.css
Labels: release
